[main]
summary=Realtime profile for OAI
include=realtime

[bootloader]
cmdline_network_latency=skew_tick=1 tsc=reliable
cmdline_realtime_rcu_nocbs=rcu_nocbs=${isolated_cores}
cmdline_realtime=isolcpus=managed_irq,domain,${isolated_cores} intel_pstate=disable nosoftlockup nohz=on nohz_full=${isolated_cores}
